version: '3.5'
services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    hostname: zookeeper
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
  clickhouse01:
    image: clickhouse/clickhouse-server
    container_name: clickhouse01
    hostname: clickhouse01
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8185:8123"
      - "127.0.0.1:9085:9000"
    volumes:
      - /var/lib/docker/volumes/clickhouse01/_data:/etc/clickhouse-server
      - /var/lib/docker/volumes/clickhouse1/_data:/var/lib/clickhouse
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server
    container_name: clickhouse02
    hostname: clickhouse02
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    volumes:
      - /var/lib/docker/volumes/clickhouse02/_data:/etc/clickhouse-server
      - /var/lib/docker/volumes/clickhouse2/_data:/var/lib/clickhouse
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
